chpPheno:
 - NAFLD

rvtestPed:
 NAFLD:   [ NAFLD, B]
 T2D:     [ T2D, D ]
 BMI:     [ BMI, C ]
 AGE:     [ age_core, C ]
 AGESQ:   [ age_core2, C ]
 SEX:     [ n_sex ]
 PC1:     [ PC1, C ]
 PC2:     [ PC2, C ]
 PC3:     [ PC3, C ]
 PC4:     [ PC4, C ]
 PC5:     [ PC5, C ]
