impPHE:
 - NAFLDadj

impCOV:
 NAFLDadj: [ NAFLDadj, B ]
 AGE: [ age, C ]
 SEX: [ FEMALE, D ]
 EtOH: [ abauditc, D ]
 T2D: [ T2D, D ]
 HTN: [ HTN, D ]
 HDL: [ p_hdl, C ]
 TG: [ p_tgl, C ]
 PC1: [ PC1, C ]
 PC2: [ PC2, C]
 PC3: [ PC3, C]
 PC4: [ PC4, C]
 PC5: [ PC5, C]
 PC6: [ PC6, C ]
 PC7: [ PC7, C]
 PC8: [ PC8, C]
 PC9: [ PC9, C]
 PC10: [ PC10, C]

impMAF:
 - "0.01"

impPOP:
 - EUR
 - AFR
 - AMR

impINFO:
 - "0.6"

