SCHEME STDERR
CUSTOMVARIABLE N_INFORMATIVE
LABEL N_INFORMATIVE AS N_INFORMATIVE

MARKER CHRCBP
FREQ AF
ALLELE ALT REF
EFFECT EFFECT
PVALUE PVALUE
STDERR SE
WEIGHT N_INFORMATIVE
STDERR SE

AVERAGEFREQ ON
MINMAXFREQ ON
COLUMNCOUNTING STRICT
GENOMICCONTROL ON
SEPERATOR WHITESPACE
PROCESS summary/chp/NAFLD/NAFLD.EUR.chp.maf0.01.rvtest.out
PROCESS summary/chp/NAFLD/NAFLD.AMR.chp.maf0.01.rvtest.out
PROCESS summary/chp/NAFLD/NAFLD.AFR.chp.maf0.01.rvtest.out

OUTFILE summary/chp/NAFLD/NAFLD.META.chp.maf0.01.meta_ .out
ANALYZE HETEROGENEITY
QUIT
