SCHEME STDERR
CUSTOMVARIABLE N_INFORMATIVE
LABEL N_INFORMATIVE AS N_INFORMATIVE

MARKER CHRCBP
FREQ AF
ALLELE ALT REF
EFFECT EFFECT
PVALUE PVALUE
STDERR SE

AVERAGEFREQ ON
MINMAXFREQ ON
COLUMNCOUNTING STRICT
SEPERATOR WHITESPACE
PROCESS summary/imp/PHECODE/PHECODE.EUR.imp.info0.6.maf0.00.rvtest.out
PROCESS summary/imp/PHECODE/PHECODE.AMR.imp.info0.6.maf0.00.rvtest.out
PROCESS summary/imp/PHECODE/PHECODE.AFR.imp.info0.6.maf0.00.rvtest.out

OUTFILE summary/imp/PHECODE/PHECODE.META.imp.info0.6.maf0.00.meta_ .out
ANALYZE HETEROGENEITY
QUIT
