SCHEME STDERR
CUSTOMVARIABLE N_INFORMATIVE
LABEL N_INFORMATIVE AS N_INFORMATIVE

MARKER CHRCBP
FREQ AF
ALLELE ALT REF
EFFECT EFFECT
PVALUE PVALUE
STDERR SE

AVERAGEFREQ ON
MINMAXFREQ ON
COLUMNCOUNTING STRICT
GENOMICCONTROL OFF
SEPERATOR WHITESPACE
PROCESS summary/imp/T2Dnew/T2Dnew.EUR.imp.info0.6.maf0.00.rvtest.out
PROCESS summary/imp/T2Dnew/T2Dnew.AMR.imp.info0.6.maf0.00.rvtest.out
PROCESS summary/imp/T2Dnew/T2Dnew.AFR.imp.info0.6.maf0.00.rvtest.out

OUTFILE summary/imp/T2Dnew/T2Dnew.META.imp.info0.6.maf0.00.meta_ .out
ANALYZE HETEROGENEITY
QUIT
